=== xoel/ADATClase/Unidad2AD/src/U2A4Ej4/Modulo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Modulo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Nome" type="xs:string"/>
        <xs:element ref="contidos"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="contidos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Bloque" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Bloque">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Titulo" type="xs:string"/>
        <xs:element name="Descripción" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="num" type="xs:string" use="required"/>
      <xs:attribute name="sesións" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== xoel/ADATClase/Unidad2AD/src/U2A4Ej4/Modulo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<Modulo xsi:noNamespaceSchemaLocation="Modulo.xsd" xsml:xsl="http://www.w3.org/2001/XMLSchema-instance">
    <Nome>Redes de Area Local</Nome>
    <contidos>
        <Bloque sesións="60" nume ="1">
            <Titulo>Sistemas de comunicacións</Titulo>
            <Descripción>Aspectos físicos, protocolos e arquitecturas de redes</Descripción>
        </Bloque>
        <Bloque sesións="50" nume ="2">
            <Titulo>Redes de Datos</Titulo>
            <Descripción>interconexiones y esas movidas</Descripción>
        </Bloque>
        <Bloque sesións="90" nume ="3">
            <Titulo>Sistemas de areas locales</Titulo>
            <Descripción>xestion area local, gordo granudo</Descripción>
        </Bloque>
        <Bloque sesións="80" nume ="4">
            <Titulo>Servizo de interne</Titulo>
            <Descripción>Gatos, memes y gordos cayendose</Descripción>
        </Bloque>
    </contidos>
</Modulo>
